# Generated by Django 5.1 on 2024-08-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_director_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Режиссёр', 'verbose_name_plural': 'Режиссёры'},
        ),
    ]
