# Generated by Django 5.1 on 2024-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_category_searchtag_review_stars_alter_review_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
        migrations.AddField(
            model_name='director',
            name='tags',
            field=models.ManyToManyField(blank=True, to='movie_app.searchtag', verbose_name='Поисковые слова'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='movie_app.searchtag', verbose_name='Поисковые слова'),
        ),
    ]
