# Generated by Django 5.1 on 2024-09-02 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_remove_review_tags_director_tags_alter_movie_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_app.director', verbose_name='Режиссёр'),
        ),
    ]
