# Generated by Django 5.1 on 2024-09-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_alter_movie_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchtag',
            options={'verbose_name': 'Поисковые слова', 'verbose_name_plural': 'Поисковые слова'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.category'),
        ),
    ]
